"""PDF 报告生成器 —— 生成每日收盘分析报告"""

from __future__ import annotations

import datetime
from pathlib import Path

from fpdf import FPDF

# ── Unicode 字体路径 ──
_DEJAVU = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
_DEJAVU_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
_DEJAVU_ITALIC = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"

# ── 颜色主题 ──
C1 = (25, 55, 109)       # 深蓝
C2 = (0, 122, 204)       # 亮蓝
CG = (0, 180, 100)       # 绿色
CR = (220, 60, 60)       # 红色
CY = (240, 180, 30)      # 黄色
CGR = (100, 100, 100)    # 灰色
CLB = (240, 242, 248)    # 浅蓝灰背景
CW = (255, 255, 255)
CB = (30, 30, 30)




class StockReport(FPDF):
    """股票分析 PDF 报告 (Unicode 支持)"""

    def __init__(self):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.set_auto_page_break(auto=True, margin=25)
        # 注册 Unicode 字体
        if Path(_DEJAVU).exists():
            self.add_font("DejaVu", "", _DEJAVU, uni=True)
            self.add_font("DejaVu", "B", _DEJAVU_BOLD, uni=True)
            self.add_font("DejaVu", "I", _DEJAVU_ITALIC, uni=True)
            self._font_family = "DejaVu"
        else:
            self._font_family = "Helvetica"

    def _ft(self, style="", size=10):
        return (self._font_family, style, size)

    # ── 页眉 ──
    def header(self):
        if self.page_no() == 1:
            return
        self.set_font(*self._ft("I", 8))
        self.set_text_color(*CGR)
        self.cell(0, 8, "AI Stock Advisor - Daily Report", align="L")
        self.cell(0, 8, f"Page {self.page_no()}", align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*C1)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font(*self._ft("I", 7))
        self.set_text_color(*CGR)
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        self.cell(0, 10, f"Generated: {now} | For reference only, not investment advice", align="C")

    # ── 封面 ──
    def add_cover(self, title: str, subtitle: str = ""):
        self.add_page()
        self.ln(50)
        self.set_font(*self._ft("B", 28))
        self.set_text_color(*C1)
        self.cell(0, 15, title, align="C", new_x="LMARGIN", new_y="NEXT")
        if subtitle:
            self.set_font(*self._ft("", 14))
            self.set_text_color(*C2)
            self.cell(0, 10, subtitle, align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(5)
        self.set_draw_color(*C2)
        self.set_line_width(0.5)
        self.line(60, self.get_y(), 150, self.get_y())
        self.ln(10)
        self.set_font(*self._ft("", 12))
        self.set_text_color(*CGR)
        self.cell(0, 8, f"Report Date: {datetime.date.today().strftime('%Y-%m-%d')}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(30)
        self.set_font(*self._ft("I", 8))
        self.set_text_color(*CGR)
        self.multi_cell(0, 5,
            "Disclaimer: This report is auto-generated by AI Stock Advisor system based on "
            "quantitative models and technical indicators. For reference only, not investment advice.", align="C")

    # ── 章节标题 ──
    def add_section(self, title: str):
        self.ln(4)
        self.set_font(*self._ft("B", 16))
        self.set_text_color(*C1)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*C2)
        self.set_line_width(0.4)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def add_sub(self, title: str):
        self.set_font(*self._ft("B", 12))
        self.set_text_color(*C2)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def add_text(self, text: str):
        self.set_font(*self._ft("", 9.5))
        self.set_text_color(*CB)
        self.multi_cell(0, 5, text)
        self.ln(2)

    def add_text_color(self, text: str, color: tuple):
        self.set_font(*self._ft("", 9.5))
        self.set_text_color(*color)
        self.multi_cell(0, 5, text)
        self.ln(1)

    # ── 评分条 ──
    def add_score_bar(self, label: str, score: float, max_score: float = 100):
        bw = 120
        bh = 6
        pct = min(score / max_score, 1.0)
        bar_color = CG if pct >= 0.65 else CY if pct >= 0.45 else CR
        self.set_font(*self._ft("", 9))
        self.set_text_color(*CB)
        self.cell(50, 6, label, align="R")
        x = self.get_x()
        y = self.get_y()
        self.set_fill_color(220, 220, 220)
        self.rect(x, y + 1, bw, bh, style="F")
        self.set_fill_color(*bar_color)
        self.rect(x, y + 1, bw * pct, bh, style="F")
        self.set_xy(x + bw + 3, y)
        self.set_font(*self._ft("B", 9))
        self.set_text_color(*bar_color)
        self.cell(20, 8, f"{score:.0f}")
        self.ln(9)

    # ── 表格 ──
    def add_table(self, headers: list[str], rows: list[list], col_widths: list[int] | None = None):
        if col_widths is None:
            col_widths = [190 // len(headers)] * len(headers)
        # header
        self.set_font(*self._ft("B", 8))
        self.set_fill_color(*C1)
        self.set_text_color(*CW)
        for i, h in enumerate(headers):
            self.cell(col_widths[i], 7, h, border=1, fill=True, align="C")
        self.ln()
        # rows
        self.set_font(*self._ft("", 8))
        fill = False
        for row in rows:
            self.set_text_color(*CB)
            if fill:
                self.set_fill_color(*CLB)
            else:
                self.set_fill_color(*CW)
            for i, cell_text in enumerate(row):
                self.cell(col_widths[i], 6, str(cell_text), border=1, fill=fill, align="C")
            self.ln()
            fill = not fill
        self.ln(3)

    # ── 分割线 ──
    def add_divider(self):
        self.set_draw_color(*CGR)
        self.set_line_width(0.2)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)


def generate_daily_report(
    market_summary: dict | None = None,
    sector_analysis: list[dict] | None = None,
    stock_analysis: list[dict] | None = None,
    portfolio_summary: dict | None = None,
    market_news: list[dict] | None = None,
    sentiments: dict | None = None,
    output_dir: str = "reports",
) -> str:
    """生成每日综合 PDF 报告"""
    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)
    today = datetime.date.today()
    filename = out_path / f"daily_report_{today.strftime('%Y%m%d')}.pdf"

    pdf = StockReport()

    # ── 封面 ──
    pdf.add_cover(
        title="Daily Stock Analysis Report",
        subtitle="AI Stock Advisor Multi-Agent System",
    )

    # ── 目录 ──
    pdf.add_page()
    pdf.add_section("Table of Contents")
    toc = [
        "1. Market Overview",
        "2. Sector Analysis",
        "3. Individual Stock Technical Scores"
        "4. Market Sentiment & News",
        "5. AI Chain Stock Picks",
        "6. Robot Industry Chain Stock Picks",
        "7. Portfolio Suggestions",
        "8. Risk Disclaimer",
    ]
    for item in toc:
        pdf.set_font(*pdf._ft("", 11))
        pdf.set_text_color(*C1)
        pdf.cell(0, 8, f"    {item}", new_x="LMARGIN", new_y="NEXT")

    # ── 1. 市场总览 ──
    pdf.add_page()
    pdf.add_section("1. Market Overview")

    if market_summary:
        indices = market_summary.get("indices", [])
        if indices:
            pdf.add_table(
                headers=["Index", "Price", "Change", "Score"],
                rows=[[
                    i.get("name", ""), str(i.get("price", "")),
                    f'{i.get("change_pct", 0):+.2f}%',
                    f'{i.get("score", 50):.0f}/100'
                ] for i in indices],
                col_widths=[50, 50, 50, 40],
            )
        outlook = market_summary.get("outlook", "")
        if outlook:
            pdf.add_sub("Market Outlook")
            pdf.add_text(outlook)

    # ── 2. 板块分析 ──
    pdf.add_section("2. Sector Analysis")

    if sector_analysis:
        rows = []
        for s in sector_analysis:
            rows.append([
                s['name'], f'{s.get("score",0):.0f}',
                f'{s.get("spread",0):+.1f}%',
                s.get("direction","-"),
                s.get("view","")[:30],
            ])
        pdf.add_table(
            headers=["Sector", "Score", "Spread", "Direction", "View"],
            rows=rows, col_widths=[35, 25, 30, 30, 70],
        )

    # ── 3. 个股评分 ──
    pdf.add_page()
    pdf.add_section("3. Individual Stock Technical Scores"
        "4. Market Sentiment & News")

    if stock_analysis:
        rows = []
        for stk in stock_analysis:
            rows.append([
                stk.get("name",""), stk.get("code",""),
                f'{stk.get("price",0):.2f}',
                f'{stk.get("score",0):.0f}/100',
                stk.get("signal","-"), stk.get("trend",""),
                f'{stk.get("rsi",0):.1f}',
            ])
        pdf.add_table(
            headers=["Name", "Code", "Price", "Score", "Signal", "Trend", "RSI"],
            rows=rows, col_widths=[35, 30, 30, 30, 25, 20, 20],
        )

        # 买入参考
        pdf.add_sub("Buy/Sell Reference")
        for stk in stock_analysis:
            color = CG if stk.get("action") in ("关注",) else CR if stk.get("action") == "回避" else CB
            text = f"{stk.get('name','')}({stk.get('code','')}): Score {stk.get('score',0):.0f}/100 | "
            text += f"Entry: {stk.get('entry_ref','N/A')} | Action: {stk.get('action','观望')}"
            if stk.get("reason"):
                text += f" -- {stk['reason']}"
            pdf.add_text_color(text, color)

    # ── 4. AI 推荐 ──
    pdf.add_page()
    pdf.add_section("5. AI Chain Stock Picks")

    ai_stocks = [s for s in (stock_analysis or []) if s.get("sector_group") == "AI"]
    if ai_stocks:
        pdf.add_table(
            headers=["Priority", "Stock", "Score", "Entry Ref", "Logic"],
            rows=[[
                s.get("priority",""), f"{s.get('name','')}({s.get('code','')})",
                f'{s.get("score",0):.0f}/100', s.get("entry_ref","-"),
                s.get("reason","")[:30],
            ] for s in ai_stocks],
            col_widths=[20, 45, 25, 40, 60],
        )

    # ── 5. 机器人推荐 ──
    pdf.add_section("6. Robot Industry Chain Stock Picks")

    robot_stocks = [s for s in (stock_analysis or []) if s.get("sector_group") == "机器人"]
    if robot_stocks:
        pdf.add_table(
            headers=["Priority", "Stock", "Score", "Entry Ref", "Logic"],
            rows=[[
                s.get("priority",""), f"{s.get('name','')}({s.get('code','')})",
                f'{s.get("score",0):.0f}/100', s.get("entry_ref","-"),
                s.get("reason","")[:30],
            ] for s in robot_stocks],
            col_widths=[20, 45, 25, 40, 60],
        )

    # ── 6. 持仓建议 ──
    pdf.add_section("7. Portfolio Suggestions")

    if portfolio_summary:
        txt = f"Total Holdings: {portfolio_summary.get('total', 0)} | "
        txt += f"Total P&L: {portfolio_summary.get('total_pnl', 0):+.2f}% | "
        txt += f"Suggested Position: {portfolio_summary.get('suggested_position', 'N/A')}"
        pdf.add_text(txt)

    # ── 7. 风险提示 ──
    pdf.add_page()
    pdf.add_section("8. Risk Disclaimer")

    risks = [
        "1. This report is auto-generated by AI models for reference only.",
        "2. Technical analysis is based on historical data and cannot fully predict future movements.",
        "3. Model accuracy is approximately 60-65%, with 35-40% error margin.",
        "4. Please combine with fundamental analysis, policy analysis for comprehensive judgment.",
        "5. Stock market involves risk. Invest prudently with position control.",
        f"6. Report generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
    ]
    for r in risks:
        pdf.set_font(*pdf._ft("", 9.5))
        pdf.set_text_color(*CGR)
        pdf.cell(0, 8, r, new_x="LMARGIN", new_y="NEXT")

    # ── 保存 ──
    pdf.output(str(filename))
    print(f"  [PDF] Report saved: {filename}")
    return str(filename)
